# Generated by Django 4.2.13 on 2024-11-14 22:49

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_image',
        ),
        migrations.AddField(
            model_name='project',
            name='project_image_cloudinary',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_image_local',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
    ]
