# Generated by Django 4.2.13 on 2024-11-15 13:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_project_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_image_local',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image_cloudinary',
            field=cloudinary.models.CloudinaryField(blank=True, default='default-placeholder.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
