# Generated by Django 4.2.13 on 2024-12-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_project_image_local_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('business_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('competitors', models.TextField(blank=True, null=True)),
                ('purpose', models.CharField(max_length=255)),
            ],
        ),
    ]
